# -*- coding: utf-8 -*-
"""Copia de promedio_notas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P2DlnMt_utWNdzlQ-jbRvq6KtuhCkNPJ
"""



"""## PROGRAMA PARA CALCULAR EL PROMEDIO DE TRES NOTAS

# Función con tres parámetros y retorno de un valor
"""

def calcular_promedio(nota1, nota2, nota3):
    promedio = (nota1 + nota2 + nota3) / 3
    return promedio


# Solicitar las notas al usuario
nota1 = float(input("Ingrese la primera nota: "))
nota2 = float(input("Ingrese la segunda nota: "))
nota3 = float(input("Ingrese la tercera nota: "))


# Llamada a la función
resultado = calcular_promedio(nota1, nota2, nota3)


# Mostrar el resultado
print("El promedio de las tres notas es:", resultado)